"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowRight, BarChart3, Check, Heart, Link2, Menu, MessageCircle, Play, ShieldCheck, Sparkles, X } from "lucide-react";
import { useState } from "react";

const features = [
  { icon: Link2, number: "01", title: "Link personal untuk setiap tamu", description: "Tamu menerima undangan dengan nama mereka sendiri. Lebih hangat, lebih berkesan, dan terasa benar-benar personal." },
  { icon: BarChart3, number: "02", title: "RSVP yang rapi dan terukur", description: "Pantau konfirmasi kehadiran, jumlah tamu, hingga catatan mereka dalam satu dashboard yang mudah dipahami." },
  { icon: MessageCircle, number: "03", title: "Bagikan lewat WhatsApp", description: "Salin link atau kirim undangan langsung melalui WhatsApp tanpa perlu berpindah-pindah aplikasi." },
];

const steps = [
  { step: "01", title: "Siapkan daftar tamu", text: "Masukkan nama dan detail tamu ke dalam daftar undangan." },
  { step: "02", title: "Buat link undangan", text: "Satu klik untuk membuat link personal untuk setiap orang." },
  { step: "03", title: "Bagikan & pantau", text: "Kirim undangan dan lihat perkembangan RSVP secara real-time." },
];

export default function HomePage() {
  const [menuOpen, setMenuOpen] = useState(false);

  return (
    <main className="relative min-h-screen overflow-hidden bg-[#fbfaf7] text-[#263229]">
      <div className="pointer-events-none absolute inset-x-0 top-0 z-0 h-190 bg-[radial-gradient(circle_at_75%_15%,rgba(205,216,166,0.38),transparent_34%),radial-gradient(circle_at_8%_23%,rgba(242,220,193,0.42),transparent_30%)]" />
      <nav className="relative z-20 mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8 lg:px-10">
        <Link href="/home" className="flex items-center gap-3" aria-label="Undangan Kita beranda"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[#263229] text-[#f7f3e9] shadow-lg shadow-[#263229]/10"><Heart size={18} fill="currentColor" strokeWidth={1.5} /></span><span className="font-serif text-2xl tracking-tight">undangan<span className="text-[#8a9a5b]">kita</span></span></Link>
        <div className="hidden items-center gap-8 font-sans text-sm text-[#697269] md:flex"><a href="#fitur" className="transition hover:text-[#263229]">Fitur</a><a href="#cara-kerja" className="transition hover:text-[#263229]">Cara kerja</a><a href="#tentang" className="transition hover:text-[#263229]">Tentang</a><Link href="/" className="transition hover:text-[#263229]">Lihat undangan</Link><Link href="/admin" className="rounded-full bg-[#263229] px-5 py-3 font-medium text-white transition hover:bg-[#4b6044]">Buka dashboard</Link></div>
        <button className="rounded-full p-2 md:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label="Buka menu" aria-expanded={menuOpen}>{menuOpen ? <X size={22} /> : <Menu size={22} />}</button>
        {menuOpen && <div className="absolute inset-x-5 top-19 rounded-2xl border border-[#e7e5dd] bg-[#fffdf9] p-4 shadow-xl md:hidden"><div className="flex flex-col gap-1 font-sans text-sm text-[#697269]"><a href="#fitur" onClick={() => setMenuOpen(false)} className="rounded-xl px-4 py-3 hover:bg-[#f2f4ea]">Fitur</a><a href="#cara-kerja" onClick={() => setMenuOpen(false)} className="rounded-xl px-4 py-3 hover:bg-[#f2f4ea]">Cara kerja</a><Link href="/" className="rounded-xl px-4 py-3 hover:bg-[#f2f4ea]">Lihat undangan</Link><Link href="/admin" className="mt-2 rounded-xl bg-[#263229] px-4 py-3 text-center text-white">Buka dashboard</Link></div></div>}
      </nav>

      <section className="relative z-10 mx-auto grid max-w-7xl items-center gap-14 px-5 pb-24 pt-14 sm:px-8 md:pt-20 lg:grid-cols-[1fr_0.9fr] lg:px-10 lg:pb-32">
        <motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.7 }}><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#d9dfc7] bg-[#f4f7ea]/80 px-4 py-2 font-sans text-[11px] font-semibold uppercase tracking-[0.2em] text-[#758650]"><Sparkles size={14} /> Untuk hari istimewa Anda</div><h1 className="max-w-3xl font-serif text-5xl leading-[0.98] tracking-[-0.04em] sm:text-7xl lg:text-[84px]">Bagikan cerita cinta, <em className="font-normal text-[#8a9a5b]">satu tamu</em> dalam satu waktu.</h1><p className="mt-7 max-w-xl font-sans text-base leading-8 text-[#697269] sm:text-lg">Undangan digital yang elegan, personal, dan mudah dikelola. Buat setiap tamu merasa istimewa sejak pertama kali menerima kabar bahagia Anda.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/admin" className="group inline-flex items-center justify-center gap-3 rounded-full bg-[#263229] px-7 py-4 font-sans text-sm font-semibold text-white shadow-xl shadow-[#263229]/15 transition hover:-translate-y-0.5 hover:bg-[#4b6044]">Mulai kelola undangan <ArrowRight size={17} className="transition group-hover:translate-x-1" /></Link><Link href="/" className="inline-flex items-center justify-center gap-3 rounded-full border border-[#d9ddd3] bg-white/60 px-7 py-4 font-sans text-sm font-semibold text-[#4d5b4b] transition hover:border-[#a8ba78] hover:bg-white"><Play size={15} fill="currentColor" /> Lihat contoh undangan</Link></div><div className="mt-10 flex items-center gap-4 font-sans text-xs text-[#858d82]"><div className="flex -space-x-2">{["R", "W", "A"].map((letter) => <span key={letter} className="flex h-8 w-8 items-center justify-center rounded-full border-2 border-[#fbfaf7] bg-[#d8e0bd] font-serif text-sm text-[#4b6044]">{letter}</span>)}</div><span><strong className="text-[#4d5b4b]">Sederhana dan berkesan.</strong><br />Dirancang untuk momen yang tak terlupakan.</span></div></motion.div>
        <motion.div initial={{ opacity: 0, scale: 0.94, y: 20 }} animate={{ opacity: 1, scale: 1, y: 0 }} transition={{ duration: 0.9, delay: 0.15 }} className="relative mx-auto w-full max-w-122.5"><div className="absolute -right-5 -top-6 h-28 w-28 rounded-full border border-[#d9dfc7] opacity-70" /><div className="absolute -bottom-8 -left-8 h-36 w-36 rounded-full bg-[#f2ddc7]/50 blur-2xl" /><div className="relative rotate-2 rounded-4xl border border-white/80 bg-[#e8edda] p-3 shadow-[0_30px_90px_rgba(54,69,48,0.16)]"><div className="rounded-3xl border border-[#a8ba78]/30 bg-[#fbfaf5] px-7 py-12 text-center sm:px-12 sm:py-16"><div className="mx-auto mb-7 flex h-14 w-14 items-center justify-center rounded-full border border-[#becd98] text-[#8a9a5b]"><Heart size={24} strokeWidth={1.2} /></div><p className="font-sans text-[10px] uppercase tracking-[0.36em] text-[#9a9f92]">The wedding of</p><h2 className="mt-4 font-serif text-5xl leading-none sm:text-6xl">Rian <span className="text-[#a8ba78]">&amp;</span> Windi</h2><div className="mx-auto my-8 h-px w-20 bg-[#b6c68e]" /><p className="font-serif text-xl italic text-[#697269]">Sabtu, 07 November 2026</p><p className="mt-2 font-sans text-[10px] uppercase tracking-[0.25em] text-[#9a9f92]">Karawang · Jawa Barat</p><div className="mt-10 rounded-xl bg-[#f2f5e8] px-4 py-3 font-sans text-xs text-[#758650]"><span className="mr-2 inline-block h-2 w-2 rounded-full bg-[#a8ba78]" /> Undangan khusus untuk Anda</div></div></div><div className="absolute -bottom-5 -right-4 flex items-center gap-3 rounded-2xl border border-[#e5e6dd] bg-white px-4 py-3 shadow-lg sm:-right-10"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#f2f5e8] text-[#8a9a5b]"><Check size={18} /></span><span className="font-sans text-xs text-[#697269]"><strong className="block text-[#263229]">RSVP tercatat</strong>Semua lebih teratur</span></div></motion.div>
      </section>

      <section id="fitur" className="relative bg-[#263229] px-5 py-20 text-[#f8f6ee] sm:px-8 lg:px-10 lg:py-24"><div className="mx-auto max-w-7xl"><div className="mb-14 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="font-sans text-[11px] font-semibold uppercase tracking-[0.3em] text-[#a8ba78]">Semua yang Anda butuhkan</p><h2 className="mt-4 max-w-xl font-serif text-4xl leading-tight sm:text-5xl">Satu ruang untuk mengatur hari bahagia.</h2></div><p className="max-w-sm font-sans text-sm leading-7 text-[#b8c0b5]">Dari daftar tamu sampai konfirmasi kehadiran, semuanya dirancang agar persiapan pernikahan terasa lebih ringan.</p></div><div className="grid gap-px overflow-hidden rounded-3xl border border-white/10 bg-white/10 md:grid-cols-3">{features.map(({ icon: Icon, number, title, description }) => <motion.div key={number} whileHover={{ backgroundColor: "rgba(255,255,255,0.08)" }} className="group bg-[#263229] p-7 transition-colors sm:p-9"><div className="flex items-center justify-between"><span className="font-sans text-xs text-[#8d9988]">{number}</span><Icon size={22} strokeWidth={1.4} className="text-[#a8ba78]" /></div><h3 className="mt-16 max-w-xs font-serif text-2xl leading-tight text-[#f8f6ee]">{title}</h3><p className="mt-4 font-sans text-sm leading-7 text-[#aeb8a9]">{description}</p><span className="mt-8 block h-px w-8 bg-[#a8ba78] transition-all group-hover:w-16" /></motion.div>)}</div></div></section>

      <section id="cara-kerja" className="px-5 py-20 sm:px-8 lg:px-10 lg:py-28"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><div><p className="font-sans text-[11px] font-semibold uppercase tracking-[0.3em] text-[#8a9a5b]">Cara kerja</p><h2 className="mt-4 font-serif text-4xl leading-tight sm:text-5xl">Dibuat sederhana, agar Anda bisa fokus pada momen penting.</h2><p className="mt-6 font-sans text-base leading-8 text-[#697269]">Tidak perlu menjadi ahli teknologi. Kelola undangan dengan alur yang intuitif dan bagikan kabar bahagia dalam hitungan menit.</p><Link href="/admin" className="mt-8 inline-flex items-center gap-2 font-sans text-sm font-semibold text-[#4d6046] hover:text-[#263229]">Mulai sekarang <ArrowRight size={16} /></Link></div><div className="space-y-3">{steps.map(({ step, title, text }) => <div key={step} className="flex gap-5 rounded-2xl border border-[#e6e7df] bg-white/60 p-5 transition hover:border-[#c6d2a8] hover:bg-white sm:gap-7 sm:p-7"><span className="font-serif text-3xl text-[#a8ba78]">{step}</span><div><h3 className="font-serif text-2xl">{title}</h3><p className="mt-1 font-sans text-sm leading-6 text-[#697269]">{text}</p></div><ArrowRight size={18} className="ml-auto mt-2 hidden text-[#a8ba78] sm:block" /></div>)}</div></div></section>

      <section id="tentang" className="px-5 pb-20 sm:px-8 lg:px-10 lg:pb-28"><div className="mx-auto max-w-7xl overflow-hidden rounded-4xl bg-[#eaf0dc] px-7 py-12 sm:px-12 lg:flex lg:items-center lg:justify-between lg:px-16"><div><div className="mb-5 flex items-center gap-2 font-sans text-xs font-semibold uppercase tracking-[0.22em] text-[#758650]"><ShieldCheck size={16} /> Tenang di setiap langkah</div><h2 className="max-w-2xl font-serif text-4xl leading-tight sm:text-5xl">Karena setiap tamu layak mendapat undangan yang istimewa.</h2></div><div className="mt-8 flex shrink-0 flex-col gap-3 font-sans text-sm text-[#697269] lg:mt-0 lg:ml-12"><span className="flex items-center gap-3"><Check size={16} className="text-[#8a9a5b]" /> Data tamu terorganisir</span><span className="flex items-center gap-3"><Check size={16} className="text-[#8a9a5b]" /> Link mudah dibagikan</span><span className="flex items-center gap-3"><Check size={16} className="text-[#8a9a5b]" /> RSVP selalu terpantau</span></div></div></section>

      <footer className="border-t border-[#e4e5dd] px-5 py-10 sm:px-8 lg:px-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-6 sm:flex-row sm:items-center"><div><Link href="/home" className="font-serif text-2xl">undangan<span className="text-[#8a9a5b]">kita</span></Link><p className="mt-2 font-sans text-xs text-[#8b9389]">Membuat momen bahagia terasa lebih dekat.</p></div><div className="flex items-center gap-5 font-sans text-xs text-[#8b9389]"><Link href="/" className="hover:text-[#263229]">Lihat undangan</Link><Link href="/admin" className="hover:text-[#263229]">Admin</Link><span>© 2026</span></div></div></footer>
    </main>
  );
}
